# Generated by Django 3.1.7 on 2023-11-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealamount',
            name='count',
            field=models.FloatField(),
        ),
    ]
