# Generated by Django 3.2.23 on 2023-12-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealamount',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
