# Generated by Django 3.2.23 on 2023-11-30 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisecategory',
            name='time',
        ),
    ]
