# Generated by Django 3.2.23 on 2023-11-13 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.center')),
            ],
        ),
    ]
