# Generated by Django 3.1.7 on 2023-10-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_foodcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='imgUrl',
            field=models.CharField(max_length=200),
        ),
    ]
